from flask_wtf import FlaskForm
from wtforms import HiddenField, SubmitField
from wtforms.validators import AnyOf, DataRequired

try:
    import emoji as emoji_lib
except ImportError:  # pragma: no cover - fallback until dependencies are installed
    emoji_lib = None


EMOJI_ALIASES = [
    ":fire:",
    ":clap:",
    ":flexed_biceps:",
    ":party_popper:",
    ":red_heart:",
    ":face_with_tears_of_joy:",
    ":smiling_face_with_heart-eyes:",
    ":raising_hands:",
    ":thumbs_up:",
    ":handshake:",
    ":partying_face:",
    ":astonished_face:",
    ":high_voltage:",
    ":glowing_star:",
    ":trophy:",
    ":check_mark_button:",
    ":rocket:",
    ":musical_notes:",
    ":hundred_points:",
    ":star-struck:",
    ":grinning_face:",
    ":smiling_face_with_sunglasses:",
    ":sparkles:",
    ":sun:",
    ":rainbow:",
    ":soccer_ball:",
    ":basketball:",
    ":runner:",
    ":person_lifting_weights:",
    ":lotus:",
    ":sparkling_heart:",
    ":blue_heart:",
    ":green_heart:",
    ":purple_heart:",
    ":orange_heart:",
    ":yellow_heart:",
    ":folded_hands:",
    ":raised_fist:",
    ":oncoming_fist:",
    ":victory_hand:",
    ":waving_hand:",
    ":OK_hand:",
    ":pinched_fingers:",
    ":crossed_fingers:",
    ":raising_hand:",
    ":hugging_face:",
    ":thinking_face:",
    ":face_with_monocle:",
    ":pleading_face:",
    ":face_holding_back_tears:",
    ":smiling_face_with_tear:",
    ":loudly_crying_face:",
    ":face_savoring_food:",
    ":drooling_face:",
    ":zany_face:",
    ":exploding_head:",
    ":sleeping_face:",
    ":eyes:",
    ":brain:",
    ":heart_on_fire:",
    ":mending_heart:",
    ":star:",
    ":dizzy:",
    ":collision:",
    ":rainbow:",
    ":sun_with_face:",
    ":crescent_moon:",
    ":snowflake:",
    ":umbrella_with_rain_drops:",
    ":seedling:",
    ":four_leaf_clover:",
    ":hibiscus:",
    ":cherry_blossom:",
    ":tulip:",
    ":rose:",
    ":sunflower:",
    ":palm_tree:",
    ":mountain:",
    ":water_wave:",
    ":globe_showing_Europe-Africa:",
    ":studio_microphone:",
    ":headphone:",
    ":musical_note:",
    ":guitar:",
    ":artist_palette:",
    ":clapper_board:",
    ":video_game:",
    ":game_die:",
    ":performing_arts:",
    ":dart:",
    ":bowling:",
    ":tennis:",
    ":american_football:",
    ":baseball:",
    ":boxing_glove:",
    ":martial_arts_uniform:",
    ":bicycle:",
    ":camping:",
    ":backpack:",
    ":trophy:",
    ":first_place_medal:",
    ":medal_sports:",
    ":alarm_clock:",
    ":hourglass_done:",
    ":memo:",
    ":pushpin:",
    ":magnifying_glass_tilted_left:",
    ":light_bulb:",
    ":hammer_and_wrench:",
    ":gear:",
    ":money_bag:",
    ":gem_stone:",
    ":crown:",
    ":rocket:",
    ":flying_saucer:",
]


FALLBACK_REACTION_EMOJIS = [
    "🔥",
    "👏",
    "💪",
    "🎉",
    "❤️",
    "😂",
    "😍",
    "🙌",
    "👍",
    "🤝",
    "🥳",
    "😮",
    "⚡",
    "🌟",
    "🏆",
    "✅",
    "🚀",
    "🎵",
    "💯",
    "🤩",
    "😀",
    "😎",
    "✨",
    "☀️",
    "🌈",
    "⚽",
    "🏀",
    "🏃",
    "🏋️",
    "🪷",
    "💖",
    "💙",
    "💚",
    "💜",
    "🧡",
    "💛",
    "🙏",
    "✊",
    "👊",
    "✌️",
    "👋",
    "👌",
    "🤌",
    "🤞",
    "🙋",
    "🤗",
    "🤔",
    "🧐",
    "🥹",
    "🥲",
    "😭",
    "😋",
    "🤤",
    "🤪",
    "🤯",
    "😴",
    "👀",
    "🧠",
    "❤️‍🔥",
    "❤️‍🩹",
    "⭐",
    "💫",
    "💥",
    "🌤️",
    "🌙",
    "❄️",
    "☔",
    "🌱",
    "🍀",
    "🌺",
    "🌸",
    "🌷",
    "🌹",
    "🌻",
    "🌴",
    "⛰️",
    "🌊",
    "🌍",
    "🎤",
    "🎧",
    "🎶",
    "🎸",
    "🎨",
    "🎬",
    "🎮",
    "🎲",
    "🎭",
    "🎯",
    "🎳",
    "🎾",
    "🏈",
    "⚾",
    "🥊",
    "🥋",
    "🚲",
    "🏕️",
    "🎒",
    "🥇",
    "🏅",
    "⏰",
    "⌛",
    "📝",
    "📌",
    "🔍",
    "💡",
    "🛠️",
    "⚙️",
    "💰",
    "💎",
    "👑",
    "🛸",
]


def resolve_reaction_emojis():
    if emoji_lib is None:
        return list(dict.fromkeys(FALLBACK_REACTION_EMOJIS))[:100]

    emojis = [
        emoji_lib.emojize(alias, language="alias")
        for alias in EMOJI_ALIASES
    ]
    return list(dict.fromkeys(emojis))[:100]


REACTION_EMOJIS = resolve_reaction_emojis()


class ReactionForm(FlaskForm):
    emoji = HiddenField(
        validators=[DataRequired(), AnyOf(REACTION_EMOJIS)],
    )
    submit = SubmitField("React")
